name: CI/CD logistik API

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Installer les dépendances
        run: |
          python -m pip install --upgrade pip
          pip install -r app/requirements.app/requirements.txt
      - name: Lancer les tests
        run: |
          echo "Aucun test pour le moment"
    
    build-and-deploy-docker:
      runs-on: ubuntu-latest
      needs: build-and-test

      steps : 
      - name: Checkout
        user: actions/checkout@v3

      - name: Build and Push Docker image